### ISSUE TITLE
in reve.ttl the "HPF" port contains error below - toggled s/b removed

### ISSUE THREAD

**Issue by Stazed** [ssj71/rkrlv2#1]
[
    a lv2:InputPort, lv2:ControlPort ;
    lv2:index 10 ;
    lv2:symbol "HPF" ;
    lv2:name "Highpass Filter" ;
    lv2:default 27 ;
    lv2:minimum 20 ;
    lv2:maximum 20000 ;
    lv2:portProperty lv2:integer ;
    lv2:portProperty lv2:toggled ;  // this should be removed...
    units:unit units:hz ;
]

Thanks!

**Comment by ssj71** [comment]
Done. Thanks so much for the bug report!
