### ISSUE TITLE
Looper loops on very short time interval instead of waiting for record to be pressed.

### ISSUE THREAD

**Issue by JivanAmara** [ssj71/rkrlv2#17]
I'm running Rakarrack v0.6.1 on Ubuntu 14.04.  My understanding of the looper is that I hit record, play some, then hit record again and that sample is available as track 1 or 2 to play along with.  What happens when I hit record is that it records a single bar, then loops it recording another single bar over it.  Hitting record a second time stops playback and hitting play doesn't start it again, as if the track was gone.

**Comment by ssj71** [comment]
It looks like you  are using the full standalone version of rakarrack. This project is a fork that ported the fx to lv2 plugins. 
I do know a bit about rakarrack though and you need to go to the settings and select the looper time in seconds and restart the program. see the audio settings section at http://rakarrack.sourceforge.net/general.html#settings
Another great looper you might try if you aren't happy with the rakarrack one is sooperlooper.

If you have additional issues the official rakarrack project is at: https://sourceforge.net/projects/rakarrack/
I'm happy to help out where I can if you can't get any answers there.

**Comment by JivanAmara** [comment]
Thanks.

On 07/06/2016 10:30 AM, ssj71 wrote:

> It looks like you are using the full standalone version of rakarrack.
> This project is a fork that ported the fx to lv2 plugins.
> I do know a bit about rakarrack though and you need to go to the
> settings and select the looper time in seconds and restart the
> program. see the audio settings section at
> http://rakarrack.sourceforge.net/general.html#settings
> Another great looper you might try if you aren't happy with the
> rakarrack one is sooperlooper.
> 
> If you have additional issues the official rakarrack project is at:
> https://sourceforge.net/projects/rakarrack/
> I'm happy to help out where I can if you can't get any answers there.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ssj71/rkrlv2/issues/17#issuecomment-230845600, or
> mute the thread
> https://github.com/notifications/unsubscribe/AAUtqFdHxO_PYSHh8tI3y88nIsiSPaYaks5qS-ZBgaJpZM4JEnqv.

## 

Cheers,

## Jivan Amara

Senior Software Developer / System Administrator
Development@JivanAmara.net
(619) 549-4497
