### ISSUE TITLE
please do a release

### ISSUE THREAD

**Issue by magnetophon** [ssj71/rkrlv2#31]
Hi @ssj71,

Great work, thanks!

It seems there have been mostly bug fixes since the latest release.
For the benefit of packagers, could you do another one?

Thanks.

**Comment by trebmuh** [comment]
+1

**Comment by ssj71** [comment]
thanks for the request. It was a good idea. New release made tonight. Enjoy!

**Comment by magnetophon** [comment]
Thank you!
