### ISSUE TITLE
Can't build getting ''unrecognized command line option''

### ISSUE THREAD

**Issue by guysoft** [ssj71/rkrlv2#32]
```
pi@zynthianos:~/rkrlv2/build $ make
Scanning dependencies of target rkrlv2
[  1%] Building CXX object lv2/CMakeFiles/rkrlv2.dir/rkrlv2.C.o
c++: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
c++: error: unrecognized command line option ‘-msse2’
c++: error: unrecognized command line option ‘-mfpmath=sse’
```
Any way to fix this?

**Comment by ssj71** [comment]
I'm guessing this is an arm build? I haven't makes made the build scripts work for arm, but if you look at the mod devices build, it must be possible. You can see their patch https://github.com/moddevices/mod-plugin-builder/blob/master/plugins/package/rkrlv2/01_no-custom-cxx-flags.patch. let me know if you're still stuck and I'll be able to help a little more next week

**Comment by guysoft** [comment]
Cool, that works.
Sending PR, not sure if you will accept it but might as well.
