### ISSUE TITLE
Mono Versions

### ISSUE THREAD

**Issue by ssj71** [ssj71/rkrlv2#4]
Per guitarix's request. Feel free to request others. I'll work on these once I have resolved all other issues.
- Linear EQ
- Compressor
- Distortion
- Parametric EQ
- WahWah
- AlienWah
- Exciter
- Expander
- ~~Shuffle~~ - this is a stereo/mid-side effect. Impossible to make mono version
- Sustainer

my requests
- Stompbox
- Mutron
- Shelfboost

**Comment by ssj71** [comment]
will do this in v2

**Comment by brummer10** [comment]
Hi

As I ain't see any progress on this, I decided now to add a "use mono Box" option in guitarix to allow to use the rkrlv2 plugs as mono plugs in guitarix.

**Comment by ssj71** [comment]
yeah I understand, just not enough time in a day for all the projects.
Thanks for working around it!
