### ISSUE TITLE
rkr Harmonizer: how does chord mode work?

### ISSUE THREAD

**Issue by cyrusadkisson** [ssj71/rkrlv2#41]
I think chord mode of rkr Harmonizer might be broken bc if you turn on chord mode, set a chord and then set wet/dry to 100% wet, the whole plugin goes silent.

If it's what I think it is, oh boy I really want it.

Any ideas? Can someone at least confirm that it is indeed broken and that I'm not doing something wrong?

**Comment by ssj71** [comment]
yes it's broken. I believe it takes a midi signal and maps the intervals, but it's been quite some time since I looked at it.

**Comment by cyrusadkisson** [comment]
Ohhhh. So "no midi" doesn't mean "don't use on midi" but rather "midi is broken". Thanks for letting me know.
