### ISSUE TITLE
wet/dry mix should be post effect

### ISSUE THREAD

**Issue by ssj71** [ssj71/rkrlv2#7]
make a common function to do wet/dry mix, panning, and LR mix
also change "LR cross" label to "mix L/R"

**Comment by brummer10** [comment]
> also change "LR cross" label to "mix L/R"

Why would you, in fact it is a Cross, you can move the applied effect from one side to the other. Or would you leave it as it is, in the other effects?

**Comment by ssj71** [comment]
@brummer10 currently it's labeled "LR Crossover" which doesn't seem right. Maybe "LR Crossmix"? I'll probably change them all to be consistent

**Comment by brummer10** [comment]
> Maybe "LR Crossmix"?

Not bad, . .
and true, a label change will indicate that something have changed behind the scene.

**Comment by ssj71** [comment]
I've decided to leave these labels and in general all the processing unless its really a bug like it was in stereoharm. I am going to do some deep refactors and this will be one of the things, but it will be in a separate v2 project.
